// Code generated by protoc-gen-go.
// source: vapi.proto
// DO NOT EDIT!

/*
Package vapi is a generated protocol buffer package.

It is generated from these files:
	vapi.proto

It has these top-level messages:
	File
	PingRequest
	PingResponse
	ListRequest
	ListResponse
*/
package vapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// primitives
type File struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// RPC Ping
type PingRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PingResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// RPC ListFiles
type ListRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListResponse struct {
	Request      *ListRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Layout       string       `protobuf:"bytes,2,opt,name=layout" json:"layout,omitempty"`
	UrlPrefix    string       `protobuf:"bytes,3,opt,name=url_prefix" json:"url_prefix,omitempty"`
	RemoteServer string       `protobuf:"bytes,4,opt,name=remote_server" json:"remote_server,omitempty"`
	Files        []*File      `protobuf:"bytes,5,rep,name=Files" json:"Files,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListResponse) GetRequest() *ListRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ListResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "vapi.File")
	proto.RegisterType((*PingRequest)(nil), "vapi.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "vapi.PingResponse")
	proto.RegisterType((*ListRequest)(nil), "vapi.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "vapi.ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for VApi service

type VApiClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	ListFiles(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type vApiClient struct {
	cc *grpc.ClientConn
}

func NewVApiClient(cc *grpc.ClientConn) VApiClient {
	return &vApiClient{cc}
}

func (c *vApiClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/vapi.VApi/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vApiClient) ListFiles(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/vapi.VApi/ListFiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VApi service

type VApiServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	ListFiles(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterVApiServer(s *grpc.Server, srv VApiServer) {
	s.RegisterService(&_VApi_serviceDesc, srv)
}

func _VApi_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(VApiServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _VApi_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(VApiServer).ListFiles(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _VApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vapi.VApi",
	HandlerType: (*VApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _VApi_Ping_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _VApi_ListFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x1b, 0xb3, 0x6d, 0xc9, 0x24, 0x2a, 0x0e, 0x08, 0xd1, 0x83, 0x96, 0x3d, 0xe9, 0xa5,
	0x42, 0xf5, 0x0b, 0x78, 0xf1, 0xe4, 0x41, 0x3c, 0x78, 0x2d, 0x2b, 0x8c, 0x75, 0x21, 0xc9, 0xae,
	0xbb, 0x9b, 0xa2, 0x7e, 0x02, 0x3f, 0xb6, 0xfb, 0x27, 0xa5, 0x81, 0xde, 0x32, 0x2f, 0x6f, 0x7e,
	0x6f, 0x5e, 0x02, 0xb0, 0x15, 0x5a, 0x2e, 0xb5, 0x51, 0x4e, 0x21, 0x0b, 0xcf, 0x9c, 0x03, 0x7b,
	0x92, 0x0d, 0x61, 0x05, 0xac, 0x13, 0x2d, 0xd5, 0xd9, 0x22, 0xbb, 0x29, 0xc2, 0x64, 0xe5, 0x2f,
	0xd5, 0x47, 0x7e, 0xca, 0xf9, 0x15, 0x94, 0x2f, 0xb2, 0xdb, 0xbc, 0xd2, 0x57, 0x4f, 0xd6, 0xe1,
	0x29, 0xcc, 0x5b, 0xb2, 0x56, 0x6c, 0x06, 0x37, 0xbf, 0x86, 0x2a, 0xbd, 0xb7, 0x5a, 0x75, 0x96,
	0x0e, 0x0d, 0xb7, 0x50, 0x3e, 0x4b, 0xeb, 0x76, 0x00, 0x4f, 0xef, 0x2d, 0x99, 0x7d, 0x96, 0x16,
	0xee, 0x33, 0x66, 0x15, 0xfc, 0x2f, 0x83, 0x2a, 0x79, 0x07, 0x18, 0x87, 0xb9, 0x49, 0x7b, 0xd1,
	0x5f, 0xae, 0xce, 0x96, 0xb1, 0xc4, 0x18, 0x78, 0x02, 0xb3, 0x46, 0xfc, 0xa8, 0xde, 0x25, 0x08,
	0x22, 0x40, 0x6f, 0x9a, 0xb5, 0x36, 0xf4, 0x21, 0xbf, 0xeb, 0x3c, 0x6a, 0xe7, 0x70, 0x6c, 0xa8,
	0x55, 0x8e, 0xd6, 0x3e, 0x7a, 0xeb, 0xd3, 0x59, 0x94, 0x2f, 0x60, 0x1a, 0xfa, 0xdb, 0x7a, 0xba,
	0xc8, 0x3d, 0x1c, 0x12, 0x3c, 0x48, 0xab, 0x16, 0xd8, 0xdb, 0xa3, 0x96, 0x78, 0x07, 0x2c, 0xd4,
	0xc3, 0x21, 0x78, 0xf4, 0x29, 0x2e, 0x71, 0x2c, 0xa5, 0x83, 0xf9, 0x04, 0x1f, 0xa0, 0x08, 0xd7,
	0x45, 0x2e, 0x1e, 0x9e, 0xbb, 0xdb, 0x1a, 0xd7, 0xe4, 0x93, 0xf7, 0x59, 0xfc, 0x2d, 0xf7, 0xff,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x40, 0x58, 0xc1, 0xa4, 0x01, 0x00, 0x00,
}
