// generated by stringer -type=Change; DO NOT EDIT

package crawl

import "fmt"

const _Change_name = "ChangeUnknownChangeNoneChangeUpdatedChangeRemoved"

var _Change_index = [...]uint8{0, 13, 23, 36, 49}

func (i Change) String() string {
	if i < 0 || i >= Change(len(_Change_index)-1) {
		return fmt.Sprintf("Change(%d)", i)
	}
	return _Change_name[_Change_index[i]:_Change_index[i+1]]
}
